### ISSUE TITLE
Privatizing assets 

### ISSUE THREAD

**Issue by mostafahussein** [Senjai/ticketee#1]
I have reached to chapter 9 - Privatizing assets , then i run rake db:seed and rails server , log in with admin account > created a ticket successfully with attachment uploaded with no errors , but the error is he can't download it again , when i select the asset it goes to the false condition "The asset you were looking for could not be found." , is that an errata on the book ? i need your help please .. thanks !

class FilesController < ApplicationController
before_filter :authenticate_user!

def show
    asset = Asset.find(params[:id])
    if  can?(:view, asset.ticket.project)
        send_file asset.asset.path, :filename => asset.asset_file_name,
                                    :content_type => asset.asset_content_type
    else
        flash[:alert] = "The asset you were looking for could not be found."
        redirect_to root_path
    end
end

end

**Comment by Senjai** [comment]
I don't define show the way you do. https://github.com/Senjai/ticketee/blob/master/app/controllers/files_controller.rb try that and see if it fixes your issue.
